#!/bin/bash
sudo apt-get install vim-gnome ctags ttf-inconsolata mercurial gnome-session-fallback openssh-server curl
wireshark tcpdump byobu build-essential python-pip ddd compizconfig-settings-manager autoconf libtool

# Git setup
git config --global user.name "Thomas Taranowski"
git config --global user.email tom@baringforge.com

# Vim setup
git clone https://github.com/baringforge/vim.git ~/.devconfig/vim
ln -s ~/.devconfig/vim/.vim ~/.vim
ln -s ~/.devconfig/vim/.vimrc ~/.vimrc

